// AUTO-GENERATED by tools/build-knowledge-cards.js — do not edit by hand.
// Source: knowledge/nodes/*.json. Regenerate with: npm run build:knowledge-cards
export const KNOWLEDGE_CARDS = {
  "emergency-fund": {
    "title": "应急基金",
    "summary": "应急基金是3-6个月生活费的现金储备，用于应对意外支出，如失业、医疗或紧急维修。",
    "limitations": [
      "金额因个人情况调整（如工作稳定性）",
      "通胀会降低现金价值",
      "过度保守可能错失投资机会"
    ],
    "href": "../../knowledge/nodes/02-foundation/emergency-fund.json"
  },
  "housing-fund-optimization": {
    "title": "公积金优化指南",
    "summary": "公积金是国内强制储蓄账户，本质上是低息储蓄+定向使用。在 FIRE 计算中通常视为受限资产（无法自由提取），但可用于房贷月供、租房、退休前一次性提取等场景。",
    "limitations": [
      "账户内利率仅 1.5% 基准，长期跑不赢通胀，本质是被锁定的低收益储蓄",
      "提取规则因城市差异大，部分场景需户口或租赁备案证明",
      "灵活就业人员需自行缴存，单位补贴部分丧失"
    ],
    "href": "../../knowledge/nodes/02-foundation/housing-fund-optimization.json"
  },
  "savings-rate": {
    "title": "储蓄率",
    "summary": "储蓄率是你收入中用于储蓄和投资的比例，是决定你积累速度的关键数字。",
    "limitations": [
      "储蓄率高不代表投资回报高",
      "过度压缩生活可能影响可持续性",
      "收入增长也会改变最佳储蓄策略"
    ],
    "href": "../../knowledge/nodes/03-accumulation/savings-rate.json"
  },
  "dual-wheel-allocation": {
    "title": "双轮配置法",
    "summary": "双轮配置法把资产分成安全轮和风险轮，既保留安全，又追求增长。",
    "limitations": [
      "安全轮回报较低，长期增长有限",
      "风险轮仍需承受市场波动",
      "需要定期检查两轮比例是否符合目标"
    ],
    "href": "../../knowledge/nodes/04-allocation/dual-wheel-allocation.json"
  },
  "fire-types": {
    "title": "FIRE 类型",
    "summary": "FIRE有多种类型，从节俭型到灵活型，关键是选择适合你的生活成本和风险承受力的方式。",
    "limitations": [
      "FIRE类型只是思路，不是硬性标准",
      "生活成本和兴趣会影响实际选择",
      "早退休不等于永远不工作"
    ],
    "href": "../../knowledge/nodes/06-freedom/fire-types.json"
  },
  "four-percent-rule": {
    "title": "4%法则",
    "summary": "4%法则是一种安全提取策略，建议从投资组合中每年提取不超过4%的资金，以确保退休金在30年内不会耗尽。",
    "limitations": [
      "基于历史数据，不保证未来市场表现",
      "假设投资组合为60%股票/40%债券",
      "未考虑税收、遗产或特殊医疗支出"
    ],
    "href": "../../knowledge/nodes/06-freedom/four-percent-rule.json"
  }
};
